// Generated by tools/build_data.js; edit JSON instead.
export const TUTORIALS_BASICS = {
  "id": "basics",
  "page": "drawing",
  "title": "tut.basics.title",
  "steps": [
    {
      "say": "tut.basics.1",
      "mode": "line",
      "click": "[data-tool=\"line\"]"
    },
    {
      "say": "tut.basics.2",
      "drag": [
        20,
        20,
        120,
        20
      ]
    },
    {
      "say": "tut.basics.3",
      "click": "[data-tool=\"circle\"]",
      "mode": "circle"
    },
    {
      "drag": [
        70,
        60,
        90,
        60
      ],
      "wait": 600
    },
    {
      "say": "tut.basics.4",
      "click": "[data-tool=\"select\"]",
      "mode": "select"
    },
    {
      "say": "tut.basics.5",
      "mouse": [
        70,
        20
      ],
      "press": true,
      "wait": 800
    }
  ]
};
